#' Add an external border to a matrix
#'
#' @param m The matrix to border
#'
#' @returns The matrix m with a 1 column and 1 row border of 0s
#' @export
#'
#' @examples
#' m <- matrix(1, 3, 3)
#' border_matrix(m)
border_matrix <- function(m){
  bordermat <- matrix(0, nrow=nrow(m)+2, ncol=ncol(m)+2)
  bordermat[2:(nrow(m)+1), 2:(ncol(m)+1)] <- m
  bordermat
}

#' Find adjancencies by stacking shifted versions of a matrix
#'
#' @param m A binary map (matrix).
#' @param bordermat m, but with a 1 column and 1 row border of 0s. Generated by [border_matrix]
#'
#' @returns A 3D array of the size of m with 8 layers. Each layer corresponds to the pixel one pixel in a given direction of the moore neighbourhood.
#' @export
#'
#' @examples
#' m <- generate_test_matrix(5)
#' find_adj_stack(m)
find_adj_stack <- function(m, bordermat = NULL) {
  # Make bordered matrix if not provided
  bordermat <- bordermat %||% border_matrix(m)
  # Create directions matrix
  dirs <- expand.grid(1:3, 1:3)
  dirs <- dirs[-5,]
  # Generate wiggled array (m shifted by dirs)
  outarr <- simplify2array(apply(dirs, 1, \(x) {bordermat[x[1]:(nrow(m)+x[1]-1), x[2]:(ncol(m)+x[2]-1)]}, simplify = 'array'))
  outarr
}

#' Map the number of white pixels that each white pixel neighbours
#'
#' @param m A binary map (matrix).
#' @param bordermat m, but with a 1 column and 1 row border of 0s. Generated by [border_matrix]
#' @param adj_stack A 3D array containing the stack of adjacencies for each pixel.
#'
#' @returns A matrix of the same dimensions as m, but with each cell containing the number of neighbouring white pixels (if the cell itself is white)
#' @export
#'
#' @examples
#' m <- generate_test_matrix(5)
#' map_junctions(m)
map_junctions <- function(m, bordermat = NULL, adj_stack = NULL) {
  # Make bordered matrix if not provided
  bordermat <- bordermat %||% border_matrix(m)
  adj_stack <- adj_stack %||% find_adj_stack(m, bordermat)

  # Calculate depth sums _quickly_
  dim(adj_stack) <- c(prod(dim(adj_stack)[1:2]), dim(adj_stack)[3])
  # TODO: Can also generate linked directions here, store as a bitmap?
  outmat <- rowSums(adj_stack)
  dim(outmat) <- dim(m)
  # Mask off non-white nodes
  outmat[!m] <- 0
  outmat
}
