.get_3x3 <- function(m, coords, bordermat = NULL) {
  if (is.null(bordermat)) {
    # You really don't want to do this each run!
    bordermat <- border_matrix(m)
  }
  bordermat[coords[1]:(coords[1]+2),coords[2]:(coords[2]+2)]
}

.get_dir_idx <- function(d = "n") {
  as.integer(c("nw" = 1, "w" = 2, "sw" = 3, "n" = 4, "middle" = 5, "s" = 6, "ne" = 7, "e" = 8, "se" = 9)[d])
}

.get_idx_dir <- function(d) {
  c("nw", "w", "sw", "n", "middle", "s", "ne", "e", "se")[d]
}

.arridx_from_idx <- function(i, dims, offset = 0) {
  arrayInd(i, dims) + offset
}

.invert_dir <- function(d) {
  10-d
}

.idx_from_arridx <- function(arrind, size) {
  (arrind[2] - 1) * size + arrind[1]
}

.find_directions <- function(m, coords, bordermat, returndf = FALSE) {
  dirs <- setdiff(which(.get_3x3(m, coords, bordermat) > 0), 5)
  if (returndf) {
    return(suppressWarnings(data.frame(row=coords[1], col=coords[2], dir = dirs)))
  }
  return(dirs)
}

#' Trace the path between two junctions over a binary map
#'
#' @param m A binary map (matrix).
#' @param startcoords A vector of the coordinates specifying the start of the path.
#' @param direction The direction to take the first step in (either a number 1:9 or a direction, e.g. 2 or 'w').
#' @param bordermat m, but with a 1 column and 1 row border of 0s. Generated by [border_matrix]
#' @param juncmat A map of the number of junctions that each cell has. Generated by [map_junctions]
#'
#' @returns A list containing the start and end coordinates of the path, the distance travelled, and the path taken.
#' @export
#'
#' @examplesIf interactive()
#' m <- matrix(FALSE, 5, 5)
#' m[3,] <- TRUE
#' m[4:5,5] <- TRUE
#' trace_path(m, c(3,1), "e")
#'
trace_path <- function(m, startcoords, direction, bordermat = NULL, juncmat = NULL) {
  # Make sure we have all the matrices to do our work
  bordermat <- bordermat %||% border_matrix(m)
  juncmat <- juncmat %||% map_junctions(m, bordermat)
  if (inherits(direction, "character")) {
    direction <- .get_dir_idx(direction)
  }

  mrows <- nrow(m)

  # Get starting context
  # context <- get_3x3(m, startcoords, bordermat)
  coords <- startcoords

  # Init tracking
  visited <- .idx_from_arridx(coords, mrows)
  pathlength <- 0
  path <- numeric()
  while (TRUE) {
    # Traverse to next location
    coords <- coords + .arridx_from_idx(direction, dims = c(3,3), offset = -2)
    lind <- .idx_from_arridx(coords, mrows)
    if (lind %in% visited) {
      stop("Path looped!")
    }
    # Successfully traversed
    if (direction %% 2 == 0) {
      pathlength <- pathlength + 1
    } else {
      pathlength <- pathlength + sqrt(2)
    }
    visited <- c(visited, lind)
    path <- c(path, direction)

    # Evaluate if we're on a junction
    juncs <- juncmat[lind]
    if (juncs != 2) {
      # print(paste0("Found ", juncs, "-node!"))
      break
    }

    # Find context
    context <- .get_3x3(m, coords, bordermat)
    # Find new direction
    direction <- setdiff(which(context > 0), c(5, .invert_dir(direction)))
  }
  # print(paste(paste(startcoords, collapse=","),"joins to", paste(coords, collapse=",")))
  # print(visited)
  # print(pathlength)
  # print(.get_idx_dir(path))
  invisible(list("start" = startcoords, "end" = as.numeric(coords), "pathlength" = pathlength, "path" = path))
}

#' Trace the path between all junctions in a binary map
#'
#' @param m A binary map (matrix).
#' @param bordermat m, but with a 1 column and 1 row border of 0s. Generated by [border_matrix]
#' @param juncmat A map of the number of junctions that each cell has. Generated by [map_junctions]
#'
#' @returns A list of lists, will eventually return an NJANet object I think.
#' @export
#'
#' @examplesIf interactive()
#' m <- matrix(FALSE, 5, 5)
#' m[3,] <- TRUE
#' m[4:5,5] <- TRUE
#' trace_all_paths(m)
trace_all_paths <- function(m, bordermat = NULL, juncmat = NULL) {
  # Make sure we have all the matrices to do our work
  bordermat <- bordermat %||% border_matrix(m)
  juncmat <- juncmat %||% map_junctions(m, bordermat)
  # Find node locations
  nodes <- which(((juncmat > 2) + (juncmat == 1)) > 0, arr.ind = TRUE)
  cli::cli_alert_info("Base number of nodes: {.val {nrow(nodes)}}")

  paths_to_trace <- apply(nodes, 1, \(x) {.find_directions(m, x, bordermat, returndf = TRUE)})
  paths_to_trace <- as.data.frame(data.table::rbindlist(paths_to_trace))

  cli::cli_alert_info("Paths to trace: {.val {nrow(paths_to_trace)}}")

  edgelist <- list()
  cli::cli_progress_bar(
    total = nrow(paths_to_trace),
    format = "Tracing paths {cli::pb_bar} {cli::pb_current}/{cli::pb_total} | ETA: {cli::pb_eta}",
    format_done = paste0(
      "{cli::col_green(cli::symbol$tick)} Traced {cli::pb_total} paths ",
      "in {cli::pb_elapsed}."),
    clear = FALSE
    )
  # TODO: Might be able to remove from the list of junctions to visit any junction/direction rows that have already been seen
  for (i in 1:nrow(paths_to_trace)) {
    out <- tryCatch({
      trace_path(m, as.numeric(paths_to_trace[i, 1:2]), paths_to_trace[i,3], bordermat = bordermat, juncmat = juncmat)
    }, error = \(e) {
      NULL
    })
    cli::cli_progress_update()

    if (is.null(out)) {
      next
    }
    edgelist <- c(edgelist, list(out))
  }
  cli::cli_progress_done()
  return(invisible(edgelist))
}
